### ISSUE TITLE
Link to documentation is broken

### ISSUE THREAD

**Issue by vkotovv** [dante-signal31/vdist#1]
Looks like the link to ReadTheDocs is broken in Readme and some other places. Take a look at [this commit](https://github.com/dante-signal31/vdist/commit/4c7c97064e1aff0c2ade8df29f685fd7afb15100).

**Comment by dante-signal31** [comment]
Please, let me know where do you find those broken links. Readme seems to be working right.

**Comment by vkotovv** [comment]
You have a link in Readme -- http://vdist-.readthedocs.io/en/latest/
It is not working for me. Also this link is present in some other places, I've provided the commit that introduced that

**Comment by dante-signal31** [comment]
It's really a weird thing. Have you tried it from different browsers and computers?

I say that because I've tried it from a different computer than the one I usually use and it seems it's working:

![image](https://user-images.githubusercontent.com/11260761/27345611-a24367ac-55ea-11e7-8ddd-7ce64b5b170e.png)

I'm not even logged at ReadTheDocs, so problem it's not about making public the doc repository.

**Comment by dante-signal31** [comment]
Ummm, trying from my smartphone I've found the same problem you described. 

It seems a DNS problem. I guess problem is that hyphen appended to vdist documentation URL root. I'm going to try to change URL and see if that makes It work.

**Comment by dante-signal31** [comment]
OK, Could you try again?

I've recreated ReadTheDocs repository with an url root with no hyphens. Now it works from my computer and from my smartphone (where it failed before).

**Comment by vkotovv** [comment]
It works now, thanks

**Comment by dante-signal31** [comment]
Great!

Thank you for reporting this issue.
